### ISSUE TITLE
New Error: Retrying setup: List object is not an iterator

### ISSUE THREAD

**Issue by Dattamick** [xannor/ha_reolink_rest#15]
![image](https://user-images.githubusercontent.com/111907581/190284770-e29f68c5-93c0-41df-8941-24f873fce1bf.png)

Seeing this after updating. I have 4 basic cams and 1 PTZ connected to NVR.

**Comment by xannor** [comment]
Right now I have issues with NVR and PTZ. I have other open issues that are related and provide more information. Closing as duplicate.
