### ISSUE TITLE
Documentation Update: Tested Devices

### ISSUE THREAD

**Issue by SergeantPup** [xannor/ha_reolink_rest#28]
Hi,

I just wanted to let you know you could add RLC-510A's to the list of tested devices.  I bought one on Amazon to try and it worked so well, I bought 3 more.  Very popular camera that's readily available at a good price point.  Folks might come looking to see if its compatible.

Thanks for the great app!

**Comment by xannor** [comment]
Thanks for the update. I am working on moving the documentation into the Wiki so doc updates to look like version upgrades to HACS.
