### ISSUE TITLE
Image streams unavailable

### ISSUE THREAD

**Issue by MisfitPunisher** [xannor/ha_reolink_rest#41]
Hello guys, amb experiencing some issues with my both cameras 810A (same firmware v3.1.0.956_22041503, Hardware No. IPC_523128M8MP and config version v3.1.0.0), with HA 2023.1.1, OS 9.4, and supervisor 2022.12.1.

Some Video streams became unavailable without reason.

Here I let you some screenshots, Thank you all!

![Captura de pantalla 2023-01-07 a les 16 13 05](https://user-images.githubusercontent.com/51487107/211157622-4ebb60e3-00d7-4e22-9d77-de70f86b36b4.png)
![Captura de pantalla 2023-01-07 a les 16 14 19](https://user-images.githubusercontent.com/51487107/211157661-751876b0-383a-4d6b-9bef-133f7750f57f.png)

**Comment by MisfitPunisher** [comment]
Solved friends! The Audio Stream MUST BE ON, and it works fine.

**Comment by xannor** [comment]
So it randomly goes offline unless audio is enabled? When it would become unavailable would there be any errors reported in the logs? If turning the audio on does resolve this, it feels like a firmware issue and not a coding issue, so it would be good to note that.

**Comment by xannor** [comment]
After some testing, and limited time. I think I am going to put this on hiatus, I would recommend using the built in version as it has fundamentally surpassed what I have built and will have better support than I can provide.
