### ISSUE TITLE
No motion recorded

### ISSUE THREAD

**Issue by sezlony** [xannor/ha_reolink_rest#42]
HA seems to not receive motion data from cameras (410W). It's very rare when some motion gets recorded by the integration, while the cameras pick up tons of events.

**App:**
![motion](https://user-images.githubusercontent.com/101760883/211508005-2ee0a746-3236-423d-b5ab-25e4972e099a.jpg)

**Sensor data:**
![HAmotionsensor](https://user-images.githubusercontent.com/101760883/211508857-bba38576-51c4-4314-ae24-b22c5c46e9b0.jpg)

Is it a setting or just a bug?

**Comment by xannor** [comment]
It is probably a bug, unfortunately right now the only two ways to know motion has occurred is either by constant polling or via an ONVIF push. ONVIF, however, can be flighty and un reliable at times so it is verily likely to cause motion to be missed. I am hoping their webhook approach will be more reliable and pushed to all of their firmware soon.

**Comment by sezlony** [comment]
do you think there is a chance for that to happen? :question: :thinking: (chineese... they are even more lazy than ONVIF...)

**Comment by sezlony** [comment]
bump

**Comment by xannor** [comment]
I saw on the "official" integration in the HA repository that there is a bug in the NVRs where they only report onvif motion on channel 0. I have also verified this bug with the first gen duo. That being said, with the rapid progress of the HA integration and my lack of progress with this one, I would recommend switching to that integration instead.

**Comment by xannor** [comment]
After some testing, and limited time. I think I am going to put this on hiatus, I would recommend using the built in version as it has fundamentally surpassed what I have built and will have better support than I can provide.
