### ISSUE TITLE
Error when trying to configure device channel

### ISSUE THREAD

**Issue by nicaruspl** [xannor/ha_reolink_rest#7]
![image](https://user-images.githubusercontent.com/40137148/184696046-19919d8f-fafe-44f4-aaac-a6fda661e7d3.png)
![image](https://user-images.githubusercontent.com/40137148/184696083-e028de95-4324-4359-817d-4844e4672a29.png)
![image](https://user-images.githubusercontent.com/40137148/184696133-b6660dc3-638e-488f-8a36-27bc762daa6e.png)

**Comment by xannor** [comment]
Could you provide which model of camera this is? I have another issue with this and I think it may be a undocumented value response.

**Comment by nicaruspl** [comment]
NVR:         Model RLN16-410 Firmware: 3.0.0.186._22062406
Cameras : RLC 810A, RLC 510A, RLC 811A, RLC 823A
